branch-defaults:
  default:
    environment: AKIAIWIGA4BZQI76CXHA-d
    group_suffix: null
global:
  application_name: AKIAIWIGA4BZQI76CXHA
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  profile: eb-cli
  sc: null
